version: '3.8'

services:
  # ------------------------------------
  # 3. PROMETHEUS (Recolección de métricas)
  # ------------------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      # Asume que tu archivo prometheus.yaml está en la misma carpeta 'monitoring/'
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command: 
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    networks:
      - practicas_mongo-network

  # ------------------------------------
  # 4. GRAFANA (Visualización de métricas)
  # ------------------------------------
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000" # Host:3001 -> Contenedor:3000
    networks:
      - practicas_mongo-network
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=nutellalirio
      - GF_SECURITY_ADMIN_PASSWORD=moritakyla
    volumes:
      - ./grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
      - ./loki-data:/loki
    ports:
      - '3100:3100'
    networks:
      - practicas_mongo-network

# ------------------------------------
# 5. REDES
# ------------------------------------
networks:
  practicas_mongo-network:
    driver: bridge